all:	clobber

clobber:
	make -C accuracy clobber
	make -C boundaries clobber
	make -C channel clobber
	make -C estuary clobber
	make -C gridding clobber
	make -C iwaves clobber
	make -C lockexchange clobber
	make -C wetdry clobber
	make -C windstress clobber
